eclipse-tractusx/managed-simple-data-exchanger-backend

charts/dftbackend/templates/deployment.yaml
charts/dftbackend/templates/postgresql-secrets.yaml
charts/dftbackend/values.yaml

@Siegfriedk  Please review it and let us know any concern.

[dft-backend] postgres dependency updated charts.

---

CHANGELOG.md
charts/dftbackend/Chart.yaml

- Change log and release version updated in CHANGELOG.MD

Change log updated.

---

.github/workflows/trivy.yml
SECURITY.md

-  updated security.md
-  trivy image scan workflow updated.

[chore|sde-v2.1.0]Update SECURITY.md and trivy image scan workflow updated.

---

CHANGELOG.md

[chore|Updated change log .md ]

---

README.md
pom.xml

This PR adds the dash tool including testscope + an updated README

chore: add dash tool including test scope

---

pom.xml

This PR adds the required legal documents to META-INF directory of the jar file

chore: add required legal documents to META-INF directory

---

CHANGELOG.md
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/configuration/DigitalTwinAssetProvider.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/controllers/ConsumerControllerTest.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/service/ConsumerControlPanelServiceTest.java
modules/sde-external-services/digital-twins/src/main/java/org/eclipse/tractusx/sde/digitaltwins/entities/response/ShellDescriptorResponseList.java
modules/sde-external-services/digital-twins/src/main/java/org/eclipse/tractusx/sde/digitaltwins/facilitator/DigitalTwinsUtility.java
modules/sde-external-services/digital-twins/src/main/java/org/eclipse/tractusx/sde/digitaltwins/gateways/external/EDCDigitalTwinProxyForLookUp.java
modules/sde-external-services/edc/pom.xml
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/api/EDCFeignClientApi.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/entities/request/asset/AssetEntryRequest.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/entities/request/asset/AssetEntryRequestFactory.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/gateways/external/EDCGateway.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/model/request/ConsumerRequest.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/model/request/Offer.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/model/request/QueryDataOfferRequest.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/services/CatalogResponseBuilder.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/services/ConsumerControlPanelService.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/services/ContractNegotiationService.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/services/LookUpDTTwin.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/util/EDCAssetLookUp.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/util/EDCAssetUrlCacheService.java
modules/sde-submodules/assembly-part-relationship/src/main/java/org/eclipse/tractusx/sde/submodels/apr/steps/DDTRUrlCacheUtility.java
modules/sde-submodules/assembly-part-relationship/src/main/java/org/eclipse/tractusx/sde/submodels/apr/steps/EDCAspectRelationshipHandlerUseCase.java
modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/steps/EDCBatchHandlerUseCase.java
modules/sde-submodules/part-as-planned/src/main/java/org/eclipse/tractusx/sde/submodels/pap/steps/EDCPartAsPlannedHandlerStep.java
modules/sde-submodules/part-site-information-as-planned/src/main/java/org/eclipse/tractusx/sde/submodels/psiap/steps/EDCPartSiteInformationAsPlannedHandlerStep.java
modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/steps/EDCPcfHandlerUseCase.java
modules/sde-submodules/serial-part-typization/src/main/java/org/eclipse/tractusx/sde/submodels/spt/steps/EDCAspectHandlerUseCase.java
modules/sde-submodules/single-level-bom-as-planned/src/main/java/org/eclipse/tractusx/sde/submodels/slbap/steps/EDCSingleLevelBoMAsPlannedHandlerStep.java
modules/sde-submodules/single-level-usage-as-built/src/main/java/org/eclipse/tractusx/sde/submodels/sluab/steps/EDCSingleLevelUsageAsBuiltHandlerUseCase.java

- Added DT asset provider configuration on start up.

[feat|sde-backend] : dt provider configuration

---

CHANGELOG.md
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/controller/ConsumerController.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/service/ConsumerService.java

- Add controller interface for download data.

[feat|sde-backend] : Use policy hub model part 2

---

CHANGELOG.md
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/controllers/ConsumerControllerTest.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/service/ConsumerControlPanelServiceTest.java
modules/sde-external-services/digital-twins/src/main/java/org/eclipse/tractusx/sde/digitaltwins/facilitator/DigitalTwinsFacilitator.java
modules/sde-external-services/edc/pom.xml
modules/sde-submodules/assembly-part-relationship/src/main/java/org/eclipse/tractusx/sde/submodels/apr/steps/DigitalTwinsAspectRelationShipCsvHandlerUseCase.java

- Add test cases for consumer interface.

[feat|sde-backend] : Use policy hub model part 3

---

CHANGELOG.md
modules/sde-core/src/main/resources/sde-open-api.yml

[feat|sde-backend] : Open api update

---

CHANGELOG.md

- Change log updated.
- version tag updated.

[chore| sdebackend ] Change log updated

---

.github/workflows/trivy.yml

chore: Trivy workflow updated

---

DEPENDENCIES

[doc]: dependency file updated

---

CHANGELOG.md
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/PcfExchangeServiceImpl.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/mapper/JsonObjectMapper.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/mapper/PolicyTemplateObjectMapper.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/service/SubmodelOrchestartorService.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/DatabaseUsecaseHandler.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/DigitalTwinUseCaseHandler.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/EDCUsecaseHandler.java

- Added new classes for multiple submodel version support implementation.

feat : Draft code changes for multi submodel version support impl part 3

---

CHANGELOG.md
DEPENDENCIES
modules/sde-core/pom.xml
modules/sde-submodules/single-level-bom-as-built/pom.xml
modules/sde-submodules/single-level-bom-as-built/single-level-bom-as-built.md
modules/sde-submodules/single-level-bom-as-built/src/main/java/org/eclipse/tractusx/sde/submodels/slbab/SingleLevelBomAsBuiltV100.java
modules/sde-submodules/single-level-bom-as-built/src/main/java/org/eclipse/tractusx/sde/submodels/slbab/SingleLevelBomAsBuiltV300.java
modules/sde-submodules/single-level-bom-as-built/src/main/resources/single-level-bom-as-built-v1.0.0.json
modules/sde-submodules/single-level-bom-as-built/src/main/resources/single-level-bom-as-built-v3.0.0.json
pom.xml

- Supported new single level bom as built submodel with multi version support.

feat : New maven module for single level bom as built submodel

---

CHANGELOG.md
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/entity/PcfResponseEntity.java
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/AsyncPushPCFDataForApproveRequest.java
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/PCFRepositoryService.java
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/PcfExchangeServiceImpl.java
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/ProxyRequestInterface.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/configuration/properties/DigitalTwinConfigurationProperties.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/constants/CommonConstants.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/constants/SubmoduleCommonColumnsConstant.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/mapper/AspectResponseFactory.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/DatabaseUsecaseStep.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/DigitalTwinUsecaseStep.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/Step.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/create/steps/impl/GenerateUrnUUID.java
modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/utils/PolicyOperationUtil.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/configuration/DigitalTwinAssetProvider.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/configuration/PCFExchangeAssetProvider.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/configuration/role/CustomPermissionEvaluator.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/processreport/repository/SubmodelCustomHistoryGenerator.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/registry/SubmodelRegistration.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/service/SubmodelOrchestartorService.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/service/SubmodelService.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/GenericSubmodelExecutor.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/DatabaseUsecaseHandler.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/constants/EDCAssetConstant.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/entities/request/asset/AssetEntryRequestFactory.java

- Refactor code for pcf, dt access API, EDC 7 to fix feature braking changes

feat | Release refactor pcf dt edc code to fix breaking change

---

CHANGELOG.md
DEPENDENCIES
modules/sde-core/pom.xml
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/SdeApplication.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/EDCUsecaseHandler.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/SubmoduleResponseHandler.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/EnablePostgreSQL.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/PostgreSQLInitializer.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/controllers/PcfExchangeControllerTest.java
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/controllers/PolicyControllerTest.java
modules/sde-core/src/test/resource/application-test.properties
modules/sde-external-services/bpn-discovery/src/main/java/org/eclipse/tractusx/sde/bpndiscovery/handler/BPNDiscoveryUseCaseHandler.java
pom.xml

- Added test cases for PCF and policy controller.

feat | Added pcf and policy test case

---

CHANGELOG.md

chore updated changelog

---

.github/workflows/dependencies.yml
CHANGELOG.md
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/AsyncPushPCFDataForApproveRequest.java
modules/pcf-exchange/src/main/java/org/eclipse/tractusx/sde/pcfexchange/service/impl/ProxyRequestInterface.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/controller/PcfExchangeController.java
modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/service/PartnerPoolService.java
modules/sde-core/src/main/resources/application.properties
modules/sde-core/src/test/java/org/eclipse/tractusx/sde/controllers/PcfExchangeControllerTest.java
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/util/EDCAssetLookUp.java

- Refactors PCF asset exchange code changes.

fix | pcf exchange code refactor

---

CONTRIBUTING.md
LICENSE-non-code
NOTICE.md

docs: update legal docs [TRG7]

---

CHANGELOG.md
modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/util/DDTRUrlCacheUtility.java

Fix | Log injection issue fixed

---

.github/workflows/trufflehog.yml

- workflow truffle-hog updated.

chore truffle-hog workflow update
