eclipse-tractusx/managed-simple-data-exchanger-backend

charts/dftbackend/Chart.yaml, charts/dftbackend/values.yaml
Hello, I would like to suggest adding the license header for the Chart.yaml file to avoid license conflicts and following tractus-x release guidelines: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
Kind regards
Maximilian Wesener
Traceability-Foss
=> doc(Chart.yaml): Add license header for trg-5-02

.github/workflows/build.yml, .github/workflows/chart-release.yml, .github/workflows/dockerbuild.yaml, .github/workflows/kics.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, .github/workflows/veracode.yaml, CHANGELOG.md, DEPENDENCIES, build/Dockerfile, modules/sde-core/pom.xml, modules/sde-core/src/main/resources/sde-open-api.yml, modules/sde-external-services/edc/src/main/java/org/eclipse/tractusx/sde/edc/model/contractoffers/ContractOfferRequestFactory.java, pom.xml
-  Updated openAPI file for kics issue.
-  release workflow added.
=> [fix|sde-v2.0.10] openapi yaml file update for kics issue.

README.md
=> docs: fix docker image url in readme

CHANGELOG.md, DEPENDENCIES, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/create/steps/impl/RecordProcessUtils.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/processreport/ProcessReportUseCase.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/processreport/model/ProcessReportPageResponse.java, modules/sde-submodules/assembly-part-relationship/src/main/java/org/eclipse/tractusx/sde/submodels/apr/model/AspectRelationship.java, modules/sde-submodules/part-as-planned/src/main/java/org/eclipse/tractusx/sde/submodels/pap/model/PartAsPlanned.java, modules/sde-submodules/part-site-information-as-planned/src/main/java/org/eclipse/tractusx/sde/submodels/psiap/model/PartSiteInformationAsPlanned.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/PcfSubmodel.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/mapper/PcfMapper.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/model/PcfAspect.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/model/PcfSubmodelResponse.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/model/ProductOrSectorSpecificRules.java, modules/sde-submodules/pcf/src/main/resources/pcf.json, pom.xml
- Update PCF schema fields for SDE
- trivy worklow fix.
=> [fix]: SDE backend : PCF schema update with security issue fixed

CHANGELOG.md, DEPENDENCIES, build/Dockerfile, pom.xml
- docker cmd updated,removed r from run command.
- fixed veracode security CVE-2023-33202(Bouncy Castle Denial of Service). 
=> [fix|sde-backend] Veracode security fix CVE-2023-33202 and docker command updated.

CHANGELOG.md, DEPENDENCIES, pom.xml
- Fixed veracode security CVE-2023-6378(logback-classic Denial Of Service): Excluded logback-classic and logback-core old versions and added newer version
=> Fix veracode security CVE-2023-6378

CHANGELOG.md, DEPENDENCIES, pom.xml
- Fixed Veracode security CVE-2023-46589(tomcat-embed-core) and CVE-2023-34053(spring-web): 
Excluded tomcat-embed-core and newer version
reason: org.apache.tomcat: tomcat-catalina(10.1.18) is vulnerable to Request Smuggling
Excluded spring-web old versions and added newer version
reason: org.springframework: spring-web (6.0.9) is vulnerable to Denial Of Service (DoS)
=> Fixed Veracode security CVE-2023-46589 and CVE-2023-34053

CHANGELOG.md, DEPENDENCIES, modules/sde-external-services/digital-twins/src/main/java/org/eclipse/tractusx/sde/digitaltwins/facilitator/DigitalTwinsFacilitator.java, modules/sde-submodules/assembly-part-relationship/src/main/java/org/eclipse/tractusx/sde/submodels/apr/steps/DigitalTwinsAspectRelationShipCsvHandlerUseCase.java, pom.xml
- Fix new dDTR support changes.
- Fixed Vulnerability logback issue of CVE-2023-6481.
=> [fix|sde-backend] : Fixed Vulnerability logback issue of CVE-2023-6481 

CHANGELOG.md, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/CommonPropEntity.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/Policies.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/PolicyModel.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/PolicyTemplateRequest.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/PolicyTemplateType.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/entities/SubmodelJsonReq.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/enums/ProgressStatusEnum.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/exception/GlobalDefaultExceptionHandler.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/exception/ServiceException.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/mapper/AspectResponseFactory.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/mapper/PolicyTemplateObjectMapper.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/utils/PolicyOperationUtil.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/PolicyTemplateValidationAsPojo.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/PolicyTemplateValidationAsString.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/SpringValidator.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/UsagePolicyValidator.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/ValidatePolicyTemplate.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/validators/ValidationService.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/controller/PolicyHubController.java
- Added Policy-hub Proxy controller.
- Added New Policy Entities and pojo classes.
=> [feat|sde-backend] : Policy-hub Proxy controller and Policy pojo added

CHANGELOG.md, NOTICE.md, README.md, build/Dockerfile
- Docker image changed to fix vulnerability.
- fix for CVE-2023-38545,CVE-2023-4911
=> [Fix|sde-backend] Docker Image changed

CHANGELOG.md, DEPENDENCIES, modules/sde-core/pom.xml, modules/sde-core/src/main/resources/sde-open-api.yml
- Postgres vulnerability CVE-2024-1597 fix
=> [fix|sde-backend] : Postgres vulnerability CVE-2024-1597 fix

CHANGELOG.md, DEPENDENCIES, pom.xml
- Fixed spring security Vulnerability CVE-2024-22234.
=> [fix|sde-backend] : spring security vulnerability CVE-2024-22234 fix

CHANGELOG.md
[For Rel-24.03]
- open api fix in sde-open-api.yml.
- Fixed Postgres vulnerability CVE-2024-1597.
- Fixed spring security Vulnerability CVE-2024-22234.
=> chore: change log and version 2.3.6 update.

CHANGELOG.md, DEPENDENCIES, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/Step.java, modules/sde-common/src/main/java/org/eclipse/tractusx/sde/common/submodel/executor/create/steps/impl/GenerateUrnUUID.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/DigitalTwinLookUpInRegistry.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/submodel/executor/step/SubmoduleResponseHandler.java, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/utils/SubmoduleUtility.java
- Added new classes for multiple submodel version support impl.
=> feat : Draft code changes for multi submodel version support impl

CHANGELOG.md, DEPENDENCIES, modules/sde-core/pom.xml, modules/sde-submodules/part-type-information/part-type-information.md, modules/sde-submodules/part-type-information/pom.xml, modules/sde-submodules/part-type-information/src/main/java/org/eclipse/tractusx/sde/submodels/pti/PartTypeInformationV100.java, modules/sde-submodules/part-type-information/src/main/resources/part-type-information-v1.0.0.json, modules/sde-submodules/serial-part/src/main/java/org/eclipse/tractusx/sde/submodels/sp/SerialPartV300.java, modules/sde-submodules/single-level-bom-as-built/src/main/java/org/eclipse/tractusx/sde/submodels/slbab/SingleLevelBomAsBuiltV100.java, modules/sde-submodules/single-level-bom-as-built/src/main/java/org/eclipse/tractusx/sde/submodels/slbab/SingleLevelBomAsBuiltV300.java, pom.xml
- Added new maven module for part type information submodel support.
=> feat : New maven module for part type information submodel 

.github/workflows/chart-release.yml, .github/workflows/code-ql.yaml, .github/workflows/dependencies.yml, .github/workflows/dockerbuild.yaml, .github/workflows/kics.yml, .github/workflows/trivy.yml, CHANGELOG.md, DEPENDENCIES, build/Dockerfile, modules/sde-core/pom.xml, pom.xml
- Dependabot bump version fix in pom.xml and DEPENDENCIES file update
=> fix | dependabot bump version fix

CHANGELOG.md, DOCKER_NOTICE.md
- chore docker notice.md updated with docker image.
- changelog updated.
=> chore docker notice.md updated

CHANGELOG.md, modules/sde-core/src/main/resources/flyway/V22__add_new_role_for_download.sql, modules/sde-core/src/main/resources/flyway/V23__add_new_role_for_auto_config.sql, modules/sde-core/src/main/resources/flyway/V24__Alter_process_report_table.sql, modules/sde-core/src/main/resources/flyway/V25__add_new_role_for_pcf_exchange.sql, modules/sde-core/src/main/resources/flyway/V26__add_new_role_for_policy_hub.sql, modules/sde-core/src/main/resources/flyway/V27__Alter_process_report_table.sql
- fixed issue Database Migrations missing for image '2.3.7'[ #191 ] 
=> fix :  Added fix for issue #191

CHANGELOG.md, DEPENDENCIES, modules/sde-core/src/main/java/org/eclipse/tractusx/sde/configuration/SecurityConfig.java, modules/sde-submodules/pcf/pcf.md, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/PCFEDCUsecaseHandler.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/PcfV600.java, modules/sde-submodules/pcf/src/main/java/org/eclipse/tractusx/sde/submodels/pcf/PcfV700.java, modules/sde-submodules/pcf/src/main/resources/pcf-v7.0.0.json, modules/sde-submodules/submodules.md
- New changes for PCF v7.0.0 support.
- Security config changes.
- Updated change log and dependency file.
=> feat | fix : New pcf submodel v 7.0.0 support changes and security file update

CHANGELOG.md, DEPENDENCIES, modules/sde-common/pom.xml, modules/sde-core/pom.xml
- Fix for #187 , #188 , #189 , #198 , #200 .
=> fix : Dependabot bump issues fix

.github/workflows/dockerbuild.yaml, .github/workflows/trivy.yml
- trivy workflow update.
- dependabot issues fix.
=> chore trivy workflow update & dependabot issue fixed.

CHANGELOG.md, DEPENDENCIES, modules/sde-core/pom.xml, pom.xml
- Dependabot bump jar version fixed for #205 , #206 , #207 , #208 , #209 .
- Trivy high security issue fixed for #CVE-2024-34750.
=> fix : Dependabot bump issue fixs and security fix for CVE-2024-24750.

CHANGELOG.md
- change log  appversion v2.4.3.
- v2.4.2 deprecated.
=> chore updated change log
